version: '3.6'

services:
  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=qlns
      - MONGO_INITDB_ROOT_USERNAME=qlns
      - MONGO_INITDB_ROOT_PASSWORD=admin_qlns
    volumes:
      - ./mongo-db/mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./mongo-db/mongodb:/data/db
      - ./mongo-db/mongoconfig:/data/configdb
    networks:
      - qlns_net

  recruitment-api:
    container_name: recruitment-api
    build: 
      context: ./recruitment-service
    depends_on:
      - my-mongodb
      - authenticate-api
    restart: always
    volumes:
      - ./recruitment-service:/usr/src/recruitment-api
      - ./recruitment-service/node_modules:/usr/src/recruitment-api/node_modules
    environment:
      - MONGO_URL=mongodb://qlns:admin_qlns@my-mongodb:27017
      - DB_NAME=qlns
      - APP_PORT=3001
    ports: 
      - '3001:3000'
    networks:
      - qlns_net
    
  staff-api:
    container_name: staff-api
    command: python -u app.py
    build: 
      context: ./staff-service
    depends_on:
      - my-mongodb
      - authenticate-api
      - recruitment-api
    restart: always
    volumes:
      - ./staff-service:/usr/src/staff-api
    environment:
      - MONGO_URL=mongodb://qlns:admin_qlns@my-mongodb:27017
      - DB_NAME=qlns
    ports: 
      - '3003:3000'
    networks:
      - qlns_net

  authenticate-api:
    container_name: authenticate-api
    build: 
      context: ./authenticate-service
    depends_on:
      - my-mongodb
    restart: always
    volumes:
      - ./authenticate-service:/usr/src/authenticate-api
    environment:
      - MONGO_URL=mongodb://qlns:admin_qlns@my-mongodb:27017
      - APP_PORT=3002
    ports: 
      - '3002:3000'
    networks:
      - qlns_net
    
  admin-frontend:
    container_name: admin-frontend
    build: 
      context: ./admin-frontend
    depends_on:
      - recruitment-api
      - staff-api
      - authenticate-api
    restart: always
    volumes:
      - ./admin-frontend:/usr/src/admin-frontend
    environment:
      - APP_PORT=8080
      - RECRUITMENT_API_URL=http://recruitment-api:3000/
      - AUTHENTICATE_API_URL=http://authenticate-api:3000/
      - STAFF_API_URL=http://staff-api:3000/
    ports: 
      - '8080:8080'
    networks:
      - qlns_net
volumes:
  mongodb:
  mongoconfig:
  usr:
  data:

networks:
  qlns_net:
    driver: bridge
