version: '3.6'

services:
  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - my-mongodb
    networks:
      - mongo_net
    
volumes:
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge